services:
  web:
    build: .
    command: gunicorn event_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DOCKERIZED=true
      - POSTGRES_DB=eventdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
